-- begin TEST_PARAISKOS_PREKE
alter table TEST_PARAISKOS_PREKE add constraint FK_TEST_PARAISKOS_PREKE_PARAISKA foreign key (PARAISKA_ID) references TEST_PARAISKA(ID)^
alter table TEST_PARAISKOS_PREKE add constraint FK_TEST_PARAISKOS_PREKE_PAKUOTE foreign key (PAKUOTE_ID) references TEST_PAKUOTE(ID)^
create index IDX_TEST_PARAISKOS_PREKE_PARAISKA on TEST_PARAISKOS_PREKE (PARAISKA_ID)^
create index IDX_TEST_PARAISKOS_PREKE_PAKUOTE on TEST_PARAISKOS_PREKE (PAKUOTE_ID)^
-- end TEST_PARAISKOS_PREKE
