alter table TEST_PARAISKOS_PREKE add constraint FK_TEST_PARAISKOS_PREKE_PAKUOTE foreign key (PAKUOTE_ID) references TEST_PAKUOTE(ID);
create index IDX_TEST_PARAISKOS_PREKE_PAKUOTE on TEST_PARAISKOS_PREKE (PAKUOTE_ID);
